apiVersion: remediation.medik8s.io/v1alpha1
kind: NodeHealthCheck
metadata:
  name: nhc-worker-default
spec:
  # mandatory
  remediationTemplate:
    kind: PoisonPillRemediationTemplate
    apiVersion: medik8s.io/v1alpha1
    name: poison-pill-default-template
    namespace: openshift-operators
  selector:
    matchExpressions:
      - key: node-role.kubernetes.io/worker
        operator: Exists
  minHealthy: "51%"
  unhealthyConditions:
    - type: Ready
      status: "False"
      duration: 60s
    - type: Ready
      status: Unknown
      duration: 60s